dow_jones_symbols:
  - MMM
  - AXP
  - AAPL
  - BA
  - CAT
  - CVX
  - CSCO
  - KO
  - DD
  - XOM
  - GE
  - GS
  - IBM
  - INTC
  - JNJ
  - JPM
  - MCD
  - MRK
  - MSFT
  - NKE
  - PFE
  - PG
  - HD
  - TRV
  - UTX
  - UNH
  - VZ
  - V
  - WMT
  - DIS
